
#'This file contains the script for the interactive online application (ShinyApp)
#'which generates results using the AHHME-B model

#loading packages
library("shiny")
library("rsconnect")
library("tidyr")
library("shinydashboard")
library("PKI")
library("packrat")
library("data.table")
library("readxl")
library("stargazer")
library("tidyverse")
library("tseries") 
library("forecast") 
library("dynlm") 
library("seastests")
library("forecast")
library("TSA")
library("epiR")
library("extraDistr")
library("MonoInc")
library("pksensi")
library("sensitivity")
library("xlsx")
library("gridExtra")
library("ggplot2")
library("reshape2")
library("here")
library("devtools")
library("multisensi")
library("rsq")
library("forcats")
library("patchwork")
library("scales")